[project]
name = "rl-frozenlake-gym-solution"
version = "0.1.0"
description = "explore Q-learning algorithm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.1",
    "matplotlib>=3.10.7",
    "pygame>=2.6.1",
]

